base: '/'
baseVariants: {  }
errorHandling: {  }
languages:
    -   title: Deutsch
        enabled: true
        locale: de_DE
        hreflang: de-DE
        base: /
        websiteTitle: ''
        navigationTitle: German
        flag: de
        languageId: 0
    -   title: English
        enabled: true
        locale: en-US
        hreflang: en-US
        base: /en/
        websiteTitle: ''
        navigationTitle: English
        fallbackType: strict
        fallbacks: ''
        flag: us
        languageId: 1
rootPageId: 1
routes: {  }
