services:

  dfg-viewer-app:
    image: ${APP_IMAGE}
    build:
      no_cache: true
    environment:
      DB_HOST: ${DB_HOST}
      T3_USER: ${APP_T3_USER}
      T3_PASSWORD: ${APP_T3_PASSWORD}
    ports:
      - ${APP_PORT}:80
    networks:
      - backend

  dfg-viewer-db:
    image: ${DB_IMAGE}
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    ports:
      - ${DB_PORT}:3306
    networks:
      - backend
volumes:
  database:
  fileadmin:
  typo3conf:
  uploads:
networks:
  backend:
