name: Publish DFG-Viewer

on:
    workflow_dispatch: # run manually

env:
    IMAGE_TAG: latest
    GIT_OWNER: markusweigelt
    GIT_REPO: dfg-viewer
    GIT_REF: docker
    REGISTRY_PATH: ghcr.io/markusweigelt/dfg-viewer

jobs:

    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Checkout DFG-Viewer repository
              uses: actions/checkout@v4
              with:
                  repository: ${{ env.GIT_OWNER }}/${{ env.GIT_REPO }}
                  ref: update-typo12
                  path: ./Docker/extensions/dfg-viewer

            - name: Checkout Kitodo.Presentation repository
              uses: actions/checkout@v4
              with:
                repository: kitodo/kitodo-presentation
                path: ./Docker/extensions/kitodo-presentation

            - name: Checkout SLUB Digital Collections repository
              uses: actions/checkout@v4
              with:
                  repository: ${{ env.GIT_OWNER }}/slub_digitalcollections
                  ref: update-typo12
                  path: ./Docker/extensions/slub_digitalcollections

            # Activate cache export feature to reduce build time of images
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Determine build args
              run: |
                  date -u +"build_date=%Y-%m-%dT%H:%M:%SZ" >> $GITHUB_ENV
                  echo "vcs_ref=`git rev-parse --short HEAD`" >> $GITHUB_ENV

            - name: Build the DFG-Viewer image from module and deploy to GitHub Container Repository
              uses: docker/build-push-action@v6
              with:
                  context: ./Docker
                  push: true
                  tags: ${{ env.REGISTRY_PATH }}:${{ env.IMAGE_TAG }}
                  build-args: |
                      BUILD_DATE=${{ env.build_date }}
                      VCS_REF=${{ env.vcs_ref }}
                      VCS_URL=https://github.com/${{ env.GIT_OWNER }}/${{ env.GIT_REPO }}/tree/${{ env.GIT_REF }}/
                  cache-from: type=gha,scope=${{ env.vcs_ref }}-image
                  cache-to: type=gha,mode=max,scope=${{ env.vcs_ref }}-image
